buchungapp/nationaal-watersportdiploma

apps/api-server/src/operation-handlers/categories/crud.test.ts
package.json
pnpm-lock.yaml
scripts/initialize.js

Updates the generator.
The generator produces about the same code, but is now using rust via wasm. This is very exciting for me! But no-so interesting for nawadi.
It is, however nice to stay up to date. So here is a pr that does that.

Update generator code

---

apps/web/src/app/(dashboard)/[location]/diplomas/page.tsx
apps/web/src/app/(dashboard)/[location]/personen/page.tsx
apps/web/src/app/(dashboard)/_components/select.tsx
apps/web/src/app/(dashboard)/_components/table-pagination.tsx
apps/web/src/app/(dashboard)/_utils/set-query-params.ts

Adds a pagination bar for tables on the persons and diploma's tables

feat: pagination for tables

---

apps/web/src/app/(dashboard)/[location]/_components/search.tsx
apps/web/src/app/(dashboard)/[location]/diplomas/page.tsx
apps/web/src/app/(dashboard)/[location]/personen/page.tsx

feat: added search to persons and certificates

---

apps/web/src/app/(dashboard)/_components/avatar.tsx
apps/web/src/app/(dashboard)/_components/badge.tsx
apps/web/src/app/(dashboard)/_components/button.tsx
apps/web/src/app/(dashboard)/_components/checkbox.tsx
apps/web/src/app/(dashboard)/_components/radio.tsx
apps/web/src/app/(dashboard)/_components/switch.tsx
apps/web/src/app/(dashboard)/_components/table.tsx

chore: changed outline color to the branding light blue

---

apps/web/src/app/(dashboard)/[location]/layout.tsx

The nav on mobile was preventing any interaction, temporarly disabled it

chore: temporarly hide nav on mobile

---

apps/web/src/app/(dashboard)/[location]/diplomas/_components/table.tsx
apps/web/src/app/(dashboard)/[location]/personen/_components/filter.tsx
apps/web/src/app/(dashboard)/[location]/personen/_components/table.tsx
apps/web/src/app/(dashboard)/[location]/personen/page.tsx
apps/web/src/app/(public)/_components/style/side-nav.tsx

Adds a filter to the persons table, with multi select

feat: person table filter

---

apps/web/src/lib/nwd.ts

This fix is part of the 'beta' branch, but we need it now for users to be able to login.

backfix login

---

apps/web/src/app/(public)/vaarlocaties/page.tsx

After discussion we concluded that showing reviews is not a core task of the NWD.

hide review stars on locations page

---

apps/web/src/app/(dashboard)/(management)/@sidebar/locatie/[location]/_components/feedback.tsx
apps/web/src/app/(dashboard)/(management)/@sidebar/locatie/[location]/layout.tsx
apps/web/src/app/(dashboard)/(management)/locatie/[location]/personen/_components/create-single-dialog.tsx
pnpm-lock.yaml

UI Feedback Form

---

apps/web/src/app/(dashboard)/(management)/@sidebar/locatie/[location]/layout.tsx
apps/web/src/app/(dashboard)/(management)/locatie/[location]/diplomas/_components/table.tsx
apps/web/src/app/(dashboard)/(management)/locatie/[location]/diplomas/page.tsx
apps/web/src/app/(dashboard)/(management)/locatie/[location]/personen/page.tsx
packages/core/src/models/course/program.schema.ts
packages/core/src/models/course/program.ts
packages/core/src/models/curriculum/curriculum.ts
packages/core/src/models/location/location.schema.ts
packages/core/src/models/location/location.ts
packages/db/migrations/0014_needy_lionheart.sql
packages/db/migrations/0015_red_warbound.sql
packages/db/migrations/meta/0014_snapshot.json
packages/db/migrations/meta/0015_snapshot.json
packages/db/migrations/meta/_journal.json
packages/db/src/schema/course.ts
packages/db/src/schema/location.ts

* Remove redundant columns + core logic for new course/program setup
* Small UI tweaks

Beta-cleanup

---

apps/web/src/app/(dashboard)/(management)/locatie/[location]/cohorten/[cohort]/(overview)/_actions/create.ts
apps/web/src/app/(dashboard)/(management)/locatie/[location]/cohorten/[cohort]/(overview)/_actions/nwd.ts
apps/web/src/app/(dashboard)/(management)/locatie/[location]/cohorten/[cohort]/(overview)/_components/create-bulk-dialog.tsx
apps/web/src/app/(dashboard)/(management)/locatie/[location]/cohorten/[cohort]/[student-allocation]/_components/actions.tsx
apps/web/src/app/(dashboard)/(management)/locatie/[location]/cohorten/[cohort]/[student-allocation]/page.tsx
apps/web/src/app/(dashboard)/(management)/locatie/[location]/personen/_components/create-bulk-dialog.tsx
apps/web/src/lib/nwd.ts
packages/core/src/models/cohort/allocation.ts
packages/core/src/models/user/user.ts

[ ] Race condition in bulk adding students
[ ] Add remove buttons for studentAllocation and studentCurriculum

Alpha fixes

---

apps/web/src/app/(dashboard)/(management)/error.tsx
packages/core/src/models/user/person.ts

When introducing the new behavior for changing a person's email in #209, we accidentally built a wrong query. This PR fixes it and also introduces an error boundary.

picked wrong id field

---

apps/web/src/app/(dashboard)/(management)/locatie/[location]/kennisbank/page.tsx
apps/web/src/app/(dashboard)/kennisbank/[id]/route.ts
apps/web/src/app/(public)/help/artikel/_content/app-vaarlocaties/cohorten-gebruiken-als-beheerder.mdx
apps/web/src/app/(public)/help/artikel/_content/app-vaarlocaties/cohorten-gebruiken-als-instructeur.mdx
apps/web/src/lib/nwd.ts
packages/core/src/models/cohort/cohort.ts
packages/core/src/models/platform/media.ts

- update help articles
- improve knowledge center downloads

20240711-feedback-round

---

apps/web/src/app/(certificate)/diploma/_utils/generate-advise.ts
apps/web/src/lib/nwd.ts

If these basic modules are not completed, don't advise to move on to next level.

Make certificate advise more precise

---

apps/web/src/app/(dashboard)/(account)/profiel/[handle]/_components/action-buttons.tsx
apps/web/src/app/(dashboard)/(account)/profiel/[handle]/_components/cohort-progress.tsx
apps/web/src/app/(dashboard)/(account)/profiel/[handle]/voortgang/[allocation-id]/page.tsx
apps/web/src/app/(dashboard)/(management)/locatie/[location]/cohorten/[cohort]/(overview)/_components/dialog-context.tsx
apps/web/src/app/(dashboard)/(management)/locatie/[location]/cohorten/[cohort]/(overview)/_components/quick-actions.tsx
apps/web/src/app/(dashboard)/(management)/locatie/[location]/cohorten/[cohort]/(overview)/_components/table-actions.tsx
apps/web/src/app/(dashboard)/(management)/locatie/[location]/cohorten/[cohort]/(overview)/diplomas/_components/students-table.tsx
apps/web/src/app/(dashboard)/(management)/locatie/[location]/cohorten/[cohort]/(overview)/diplomas/_components/table-actions.tsx
apps/web/src/app/(dashboard)/(management)/locatie/[location]/cohorten/[cohort]/(overview)/instructeurs/_components/instructors-table.tsx
apps/web/src/app/(dashboard)/(management)/locatie/[location]/cohorten/[cohort]/(overview)/layout.tsx
apps/web/src/app/(dashboard)/(management)/locatie/[location]/cohorten/[cohort]/[student-allocation]/_components/actions.tsx
apps/web/src/app/(dashboard)/(management)/locatie/[location]/cohorten/[cohort]/[student-allocation]/_components/course-card.tsx
apps/web/src/app/(dashboard)/(management)/locatie/[location]/cohorten/[cohort]/[student-allocation]/page.tsx
apps/web/src/app/(dashboard)/(management)/locatie/[location]/personen/_components/dialog-context.tsx
apps/web/src/app/(dashboard)/_components/dropdown.tsx

Also require all cohort progress to be removed before allowing to remove a program from a allocation.

UI: Display time in localtime and wrap dropdown labels in <DropdownLabel>

---

apps/web/src/app/(dashboard)/(management)/locatie/[location]/cohorten/_components/filter.tsx
apps/web/src/app/(dashboard)/(management)/locatie/[location]/cohorten/_components/table.tsx
apps/web/src/app/(dashboard)/(management)/locatie/[location]/cohorten/page.tsx

feat: added filter button to cohorts table

---

apps/web/src/app/(dashboard)/(management)/locatie/[location]/cohorten/[cohort]/[student-allocation]/_components/course-card.tsx
apps/web/src/app/(dashboard)/(management)/locatie/[location]/cohorten/[cohort]/[student-allocation]/page.tsx

chore: added external link icon to course and student in cohort student overwiew

---

apps/web/src/app/(dashboard)/(management)/not-found.tsx

feat: 404 page for dashboard

---

apps/web/src/app/(dashboard)/(management)/locatie/[location]/cohorten/[cohort]/(overview)/instructeurs/_components/instructors-table.tsx
apps/web/src/app/(dashboard)/(management)/locatie/[location]/cohorten/[cohort]/(overview)/instructeurs/page.tsx

feat: instructeurs person page link and default instructor role

---

apps/web/package.json
apps/web/src/app/(dashboard)/(management)/locatie/[location]/cohorten/[cohort]/(overview)/_components/students-table.tsx
apps/web/src/app/(dashboard)/(management)/locatie/[location]/cohorten/[cohort]/[student-allocation]/_components/course-card.tsx
apps/web/src/app/(dashboard)/(management)/locatie/[location]/cohorten/[cohort]/[student-allocation]/_components/timeline.tsx
apps/web/src/app/(dashboard)/(management)/locatie/[location]/cohorten/[cohort]/[student-allocation]/page.tsx
apps/web/src/app/(dashboard)/(management)/locatie/[location]/cohorten/page.tsx
apps/web/src/lib/flags.ts
packages/core/src/models/cohort/student-progress.ts
pnpm-lock.yaml

Adds a timeline to the course card

feat: course card timeline

---

apps/web/src/app/(public)/actueel/(article)/TKFTErzR-9-maanden-nwd-mijlpalen-en-ambities/page.mdx

I finally received permission from the three parties involved to post the quote.

Add quotes to blog post

---

packages/core/src/models/certificate/certificate.ts
packages/core/src/models/user/person.ts

Adds:
* Person.list: filter by userId as an array + filter by personId single and as array
Fixes:
* List certificates speed by using less queries

fix: added support for person.list by person ids

---

packages/db/migrations/0026_jazzy_nightmare.sql
packages/db/migrations/meta/0026_snapshot.json
packages/db/migrations/meta/_journal.json
packages/db/src/schema/authn.ts
packages/db/src/schema/authz.ts
packages/db/src/schema/certificate.ts
packages/db/src/schema/cohort.ts
packages/db/src/schema/course.ts
packages/db/src/schema/curriculum.ts
packages/db/src/schema/location.ts
packages/db/src/schema/marketing/cashback.ts
packages/db/src/schema/media.ts
packages/db/src/schema/platform.ts
packages/db/src/schema/progress.ts
packages/db/src/schema/user.ts
pnpm-lock.yaml

Updates all pgTable statements to use the new array notation for extra config

chore: updated all pgTable calls to use new array notation

---

apps/api-server/src/authentication-handlers/open-id.ts
apps/web/src/app/(dashboard)/(account)/account/page.tsx
apps/web/src/app/(dashboard)/(management)/locatie/[location]/diplomas/page.tsx
apps/web/src/app/(dashboard)/(management)/locatie/[location]/diplomas/search-params.ts
apps/web/src/app/(dashboard)/(management)/locatie/[location]/personen/_components/table.tsx
apps/web/src/app/(dashboard)/(management)/locatie/[location]/personen/page.tsx
apps/web/src/app/(dashboard)/_lib/search-parser.ts
apps/web/src/lib/nwd.ts
packages/core/src/models/certificate/certificate.ts
packages/core/src/models/user/person.ts
packages/db/migrations/0027_previous_toad.sql
packages/db/migrations/0027_youthful_leo.sql
packages/db/migrations/meta/0027_snapshot.json
packages/db/migrations/meta/_journal.json
packages/db/package.json
packages/db/src/schema/user.ts
packages/scripts/src/add-certificate.ts
packages/scripts/src/add-location-admin.ts

**Adds**
- Postgresql full text search to location persons page
**Fixes**
- Spaces not being decoded correctly in search query

feat: person search using postgresql, fixed spaces in search query

---

apps/web/package.json
apps/web/src/lib/flags.ts
pnpm-lock.yaml

Updates the flags package as there is a vulnerability in the current version

chore: updated flags package

---

apps/web/src/app/(dashboard)/(management)/locatie/[location]/cohorten/[cohort]/(overview)/layout.tsx

Fixed by adding margin on the bottom of mobile devices

fix: cohort table bulk actions overlapping with checkbox on mobile

---

packages/scripts/src/update-user-email.ts

Updates a users email in the supabase auth and the `user` table

feat: update user email, with auth user

---

apps/web/src/app/(dashboard)/(management)/locatie/[location]/personen/[id]/_components/person-summary.tsx

NWD-40 | feat: added nwd id in description list on person page

---

apps/web/src/app/(dashboard)/(management)/_components/search.tsx
apps/web/src/app/(dashboard)/(management)/locatie/[location]/kennisbank/_components/files-table.tsx
apps/web/src/app/(dashboard)/(management)/locatie/[location]/kennisbank/page.tsx
apps/web/src/lib/nwd.ts
packages/core/src/models/platform/media.ts
packages/db/migrations/0029_wakeful_unus.sql
packages/db/migrations/meta/0029_snapshot.json
packages/db/migrations/meta/_journal.json
packages/db/src/schema/media.ts

feat: knowledge base search

---

apps/web/src/app/(dashboard)/(account)/profiel/[handle]/_components/logbook/logbook-table.tsx
apps/web/src/app/(dashboard)/(account)/profiel/[handle]/_components/logbook/logbook.tsx
apps/web/src/app/(dashboard)/(account)/profiel/[handle]/_components/progress/progress-card.tsx
apps/web/src/app/(dashboard)/(account)/profiel/[handle]/_components/watersport-certificates-section.tsx
apps/web/src/app/(dashboard)/(account)/profiel/[handle]/page.tsx
apps/web/src/app/_components/animated-wave.tsx
apps/web/src/lib/nwd.ts

this could still use some more polishing, but it's good enough for release!

add empty states to external certificates and logbook

---

apps/web/src/app/(dashboard)/(management)/locatie/[location]/cohorten/[cohort]/(overview)/diplomas/_components/table-actions.tsx
apps/web/src/app/(dashboard)/(management)/locatie/[location]/diplomas/_components/table-actions.tsx
apps/web/src/app/_actions/certificate/download-certificates-action.ts
apps/web/src/app/api/export/certificate/pdf/bulk/[id]/route.ts
apps/web/src/lib/generate-certificate-pdf.ts
apps/web/src/lib/nwd.ts
packages/core/src/models/certificate/certificate.ts

feat: allow printing of all completed modules on a certificate

---

apps/web/src/app/(dashboard)/(management)/secretariaat/gebruikers/[personId]/_components/personalia/action-button-dropdown.tsx

chore: added 'account' button on person page for secretariaat
